export const brandsList = [
  {
    name: "Aston Martin",
    imageUrl: "/brands/aston-martin-logo.png",
    href: "/aston-martin",
  },
  {
    name: "Audi",
    imageUrl: "/brands/audi-logo.png",
    href: "/audi",
  },
  {
    name: "Bentley",
    imageUrl: "/brands/bentley-logo.png",
    href: "/bentley",
  },
  {
    name: "BMW",
    imageUrl: "/brands/bmw-logo.png",
    href: "/bmw",
  },
  {
    name: "BYD",
    imageUrl: "/brands/byd-logo.png",
    href: "/byd",
  },
  {
    name: "Chery",
    imageUrl: "/brands/chery-logo.png",
    href: "/chery",
  },
  {
    name: "Chevrolet",
    imageUrl: "/brands/chevrolet-logo.png",
    href: "/chevrolet",
  },
  {
    name: "Chrysler",
    imageUrl: "/brands/chrysler-logo.png",
    href: "/chrysler",
  },
  {
    name: "Citroen",
    imageUrl: "/brands/citroen-logo.png",
    href: "/citroen",
  },
  {
    name: "Dodge",
    imageUrl: "/brands/dodge-logo.png",
    href: "/dodge",
  },
  {
    name: "Ferrari",
    imageUrl: "/brands/ferrari-logo.png",
    href: "/ferrari",
  },
  {
    name: "Fiat",
    imageUrl: "/brands/fiat-logo.png",
    href: "/fiat",
  },
  {
    name: "Ford",
    imageUrl: "/brands/ford-logo.png",
    href: "/ford",
  },
  {
    name: "GAC",
    imageUrl: "/brands/gac-logo.png",
    href: "/gac",
  },
  {
    name: "GWM",
    imageUrl: "/brands/gwm-logo.png",
    href: "/gwm",
  },
  {
    name: "Honda",
    imageUrl: "/brands/honda-logo.png",
    href: "/honda",
  },
  {
    name: "Hyundai",
    imageUrl: "/brands/hyundai-logo.png",
    href: "/hyundai",
  },
  {
    name: "Jaguar",
    imageUrl: "/brands/jaguar-logo.png",
    href: "/jaguar",
  },
  {
    name: "Jeep",
    imageUrl: "/brands/jeep-logo.png",
    href: "/jeep",
  },
  {
    name: "Kia",
    imageUrl: "/brands/kia-logo.png",
    href: "/kia",
  },
  {
    name: "Lamborghini",
    imageUrl: "/brands/lamborghini-logo.png",
    href: "/lamborghini",
  },
  {
    name: "Land-rover",
    imageUrl: "/brands/land-rover-logo.png",
    href: "/land-rover",
  },
  {
    name: "Lexus",
    imageUrl: "/brands/lexus-logo.png",
    href: "/lexus",
  },
  {
    name: "Maserati",
    imageUrl: "/brands/maserati-logo.png",
    href: "/maserati",
  },
  {
    name: "Mclaren",
    imageUrl: "/brands/mclaren-logo.png",
    href: "/mclaren",
  },
  {
    name: "Mercedes",
    imageUrl: "/brands/mercedes-logo.png",
    href: "/mercedes",
  },
  {
    name: "Mini",
    imageUrl: "/brands/mini-logo.png",
    href: "/mini",
  },
  {
    name: "Mitsubishi",
    imageUrl: "/brands/mitsubishi-logo.png",
    href: "/mitsubishi",
  },
  {
    name: "Nissan",
    imageUrl: "/brands/nissan-logo.png",
    href: "/nissan",
  },
  {
    name: "Omoda-Jaecoo",
    imageUrl: "/brands/omoda-jaecoo-logo.png",
    href: "/omoda-jaecoo",
  },
  {
    name: "Peugeot",
    imageUrl: "/brands/peugeot-logo.png",
    href: "/peugeot",
  },
  {
    name: "Porsche",
    imageUrl: "/brands/porsche-logo.png",
    href: "/porsche",
  },
  {
    name: "Ram",
    imageUrl: "/brands/ram-logo.png",
    href: "/ram",
  },
  {
    name: "Renault",
    imageUrl: "/brands/renault-logo.png",
    href: "/renault",
  },
  {
    name: "Smart",
    imageUrl: "/brands/smart-logo.png",
    href: "/smart",
  },
  {
    name: "Subaru",
    imageUrl: "/brands/subaru-logo.png",
    href: "/subaru",
  },
  {
    name: "Tesla",
    imageUrl: "/brands/tesla-logo.png",
    href: "/tesla",
  },
  {
    name: "Toyota",
    imageUrl: "/brands/toyota-logo.png",
    href: "/toyota",
  },
  {
    name: "Troller",
    imageUrl: "/brands/troller-logo.png",
    href: "/troller",
  },
  {
    name: "Volkswagen",
    imageUrl: "/brands/volkswagen-logo.png",
    href: "/volkswagen",
  },
  {
    name: "Volvo",
    imageUrl: "/brands/volvo-logo.png",
    href: "/volvo",
  },
];

export const featuredCars = [
  {
    id: "1",
    carName: "Corolla",
    carBrand: "Toyota",
    carModel: "2.0 vvt-ie flex xei direct shift",
    carPrice: 11590000,
    yearFab: "2019",
    yearModel: "2020",
    km: "50.000",
    fuel: "Flex",
    shift: "Automático",
    carPlate: "S**-***1",
    carColor: "Cinza",
    carImgUrl: "https://i.ibb.co/TD116X8h/car-featured.jpg",
    liked: "true",
  },
  {
    id: "2",
    carName: "Onix",
    carBrand: "Chevrolet",
    carModel: "plus 1.0 turbo ltz at sedan",
    carPrice: 8390000,
    yearFab: "2023",
    yearModel: "2024",
    km: "65.000",
    fuel: "Flex",
    shift: "Automático",
    carPlate: "S**-***1",
    carColor: "Branco",
    carImgUrl: "https://s3.carro57.com.br/FC/3215/6791961_0_B_2c142048d1.jpeg",
    liked: "false",
  },
  {
    id: "3",
    carName: "Renegade",
    carBrand: "Jeep",
    carModel: "1.8 at",
    carPrice: 6990000,
    yearFab: "2020",
    yearModel: "2020",
    km: "33.000",
    fuel: "Flex",
    shift: "Manual",
    carPlate: "F**-***3",
    carColor: "Branco",
    carImgUrl: "https://s3.carro57.com.br/FC/3215/7201587_10_B_40358db79a.jpeg",
    liked: "true",
  },
  {
    id: "4",
    carName: "Cooper",
    carBrand: "Mini",
    carModel: "spcman",
    carPrice: 7290000,
    yearFab: "2013",
    yearModel: "2014",
    km: "89.000",
    fuel: "Gasolina",
    shift: "Manual",
    carPlate: "F**-***3",
    carColor: "Marrom",
    carImgUrl: "https://s3.carro57.com.br/FC/3215/7190500_11_B_43bd117c73.jpeg",
    liked: "false",
  },
];
