export const brandsList = [
  {
    name: "Aston Martin",
    imageUrl: "/brands/aston-martin-logo.png",
    slug: "aston-martin",
    createdArt: new Date(),
  },
  {
    name: "Audi",
    imageUrl: "/brands/audi-logo.png",
    slug: "audi",
    createdArt: new Date(),
  },
  {
    name: "Bentley",
    imageUrl: "/brands/bentley-logo.png",
    slug: "bentley",
    createdArt: new Date(),
  },
  {
    name: "BMW",
    imageUrl: "/brands/bmw-logo.png",
    slug: "bmw",
    createdArt: new Date(),
  },
  {
    name: "BYD",
    imageUrl: "/brands/byd-logo.png",
    slug: "byd",
    createdArt: new Date(),
  },
  {
    name: "Chery",
    imageUrl: "/brands/chery-logo.png",
    slug: "chery",
    createdArt: new Date(),
  },
  {
    name: "Chevrolet",
    imageUrl: "/brands/chevrolet-logo.png",
    slug: "chevrolet",
    createdArt: new Date(),
  },
  {
    name: "Chrysler",
    imageUrl: "/brands/chrysler-logo.png",
    slug: "chrysler",
    createdArt: new Date(),
  },
  {
    name: "Citroen",
    imageUrl: "/brands/citroen-logo.png",
    slug: "citroen",
    createdArt: new Date(),
  },
  {
    name: "Dodge",
    imageUrl: "/brands/dodge-logo.png",
    slug: "dodge",
    createdArt: new Date(),
  },
  {
    name: "Ferrari",
    imageUrl: "/brands/ferrari-logo.png",
    slug: "ferrari",
    createdArt: new Date(),
  },
  {
    name: "Fiat",
    imageUrl: "/brands/fiat-logo.png",
    slug: "fiat",
    createdArt: new Date(),
  },
  {
    name: "Ford",
    imageUrl: "/brands/ford-logo.png",
    slug: "ford",
    createdArt: new Date(),
  },
  {
    name: "GAC",
    imageUrl: "/brands/gac-logo.png",
    slug: "gac",
    createdArt: new Date(),
  },
  {
    name: "GWM",
    imageUrl: "/brands/gwm-logo.png",
    slug: "gwm",
    createdArt: new Date(),
  },
  {
    name: "Honda",
    imageUrl: "/brands/honda-logo.png",
    slug: "honda",
    createdArt: new Date(),
  },
  {
    name: "Hyundai",
    imageUrl: "/brands/hyundai-logo.png",
    slug: "hyundai",
    createdArt: new Date(),
  },
  {
    name: "Jaguar",
    imageUrl: "/brands/jaguar-logo.png",
    slug: "jaguar",
    createdArt: new Date(),
  },
  {
    name: "Jeep",
    imageUrl: "/brands/jeep-logo.png",
    slug: "jeep",
    createdArt: new Date(),
  },
  {
    name: "Kia",
    imageUrl: "/brands/kia-logo.png",
    slug: "kia",
    createdArt: new Date(),
  },
  {
    name: "Lamborghini",
    imageUrl: "/brands/lamborghini-logo.png",
    slug: "lamborghini",
    createdArt: new Date(),
  },
  {
    name: "Land-rover",
    imageUrl: "/brands/land-rover-logo.png",
    slug: "land-rover",
    createdArt: new Date(),
  },
  {
    name: "Lexus",
    imageUrl: "/brands/lexus-logo.png",
    slug: "lexus",
    createdArt: new Date(),
  },
  {
    name: "Maserati",
    imageUrl: "/brands/maserati-logo.png",
    slug: "maserati",
    createdArt: new Date(),
  },
  {
    name: "Mclaren",
    imageUrl: "/brands/mclaren-logo.png",
    slug: "mclaren",
    createdArt: new Date(),
  },
  {
    name: "Mercedes",
    imageUrl: "/brands/mercedes-logo.png",
    slug: "mercedes",
    createdArt: new Date(),
  },
  {
    name: "Mini",
    imageUrl: "/brands/mini-logo.png",
    slug: "mini",
    createdArt: new Date(),
  },
  {
    name: "Mitsubishi",
    imageUrl: "/brands/mitsubishi-logo.png",
    slug: "mitsubishi",
    createdArt: new Date(),
  },
  {
    name: "Nissan",
    imageUrl: "/brands/nissan-logo.png",
    slug: "nissan",
    createdArt: new Date(),
  },
  {
    name: "Omoda-Jaecoo",
    imageUrl: "/brands/omoda-jaecoo-logo.png",
    slug: "omoda-jaecoo",
    createdArt: new Date(),
  },
  {
    name: "Peugeot",
    imageUrl: "/brands/peugeot-logo.png",
    slug: "peugeot",
    createdArt: new Date(),
  },
  {
    name: "Porsche",
    imageUrl: "/brands/porsche-logo.png",
    slug: "porsche",
    createdArt: new Date(),
  },
  {
    name: "Ram",
    imageUrl: "/brands/ram-logo.png",
    slug: "ram",
    createdArt: new Date(),
  },
  {
    name: "Renault",
    imageUrl: "/brands/renault-logo.png",
    slug: "renault",
    createdArt: new Date(),
  },
  {
    name: "Smart",
    imageUrl: "/brands/smart-logo.png",
    slug: "smart",
    createdArt: new Date(),
  },
  {
    name: "Subaru",
    imageUrl: "/brands/subaru-logo.png",
    slug: "subaru",
    createdArt: new Date(),
  },
  {
    name: "Tesla",
    imageUrl: "/brands/tesla-logo.png",
    slug: "tesla",
    createdArt: new Date(),
  },
  {
    name: "Toyota",
    imageUrl: "/brands/toyota-logo.png",
    slug: "toyota",
    createdArt: new Date(),
  },
  {
    name: "Troller",
    imageUrl: "/brands/troller-logo.png",
    slug: "troller",
    createdArt: new Date(),
  },
  {
    name: "Volkswagen",
    imageUrl: "/brands/volkswagen-logo.png",
    slug: "volkswagen",
    createdArt: new Date(),
  },
  {
    name: "Volvo",
    imageUrl: "/brands/volvo-logo.png",
    slug: "volvo",
    createdArt: new Date(),
  },
];

export const featuredCars = [
  {
    id: "1",
    carName: "Corolla",
    carBrand: "Toyota",
    carModel: "2.0 vvt-ie flex xei direct shift",
    carPrice: 11590000,
    yearFab: "2019",
    yearModel: "2020",
    km: "50.000",
    fuel: "Flex",
    shift: "Automático",
    carPlate: "S**-***1",
    carColor: "Cinza",
    carImgUrl: "https://i.ibb.co/TD116X8h/car-featured.jpg",
    liked: "true",
  },
  {
    id: "2",
    carName: "Onix",
    carBrand: "Chevrolet",
    carModel: "plus 1.0 turbo ltz at sedan",
    carPrice: 8390000,
    yearFab: "2023",
    yearModel: "2024",
    km: "65.000",
    fuel: "Flex",
    shift: "Automático",
    carPlate: "S**-***1",
    carColor: "Branco",
    carImgUrl: "https://s3.carro57.com.br/FC/3215/6791961_0_B_2c142048d1.jpeg",
    liked: "false",
  },
  {
    id: "3",
    carName: "Renegade",
    carBrand: "Jeep",
    carModel: "1.8 at",
    carPrice: 6990000,
    yearFab: "2020",
    yearModel: "2020",
    km: "33.000",
    fuel: "Flex",
    shift: "Manual",
    carPlate: "F**-***3",
    carColor: "Branco",
    carImgUrl: "https://s3.carro57.com.br/FC/3215/7201587_10_B_40358db79a.jpeg",
    liked: "true",
  },
  {
    id: "4",
    carName: "Cooper",
    carBrand: "Mini",
    carModel: "spcman",
    carPrice: 7290000,
    yearFab: "2013",
    yearModel: "2014",
    km: "89.000",
    fuel: "Gasolina",
    shift: "Manual",
    carPlate: "F**-***3",
    carColor: "Marrom",
    carImgUrl: "https://s3.carro57.com.br/FC/3215/7190500_11_B_43bd117c73.jpeg",
    liked: "false",
  },
];

export const carDetails = {
  id: "1",
  carName: "Corolla",
  carBrand: "Toyota",
  carModel: "2.0 vvt-ie flex xei direct shift",
  carPrice: 11590000,
  yearFab: "2019",
  yearModel: "2020",
  km: "50.000",
  fuel: "Flex",
  carColor: "Cinza",
  carPlate: "S**-***1",
  options: [
    {
      option: "Airbag",
    },
    {
      option: "Alarm",
    },
    {
      option: "Ar-condicionado",
    },
    {
      option: "Ar quente",
    },
    {
      option: "Banco de Couro",
    },
    {
      option: "Cambio automático",
    },
    {
      option: "Retrovisor elétrico",
    },
    {
      option: "Rodas de liga leve",
    },
    {
      option: "Trava elétrica",
    },
    {
      option: "Vidros elétricos",
    },
    {
      option: "Banco elétrico",
    },
    {
      option: "Capota Marítima",
    },
    {
      option: "Chave Cópia/reserva",
    },
  ],
  carDetails:
    "CARRO EM ÓTIMO ESTADO DE CONSERVAÇÃO, VENHA CONFERIR. Financiamento facilitado, acesse nosso estoque: A melhor avaliação do seu veículo!!! Venha fazer uma visita! Veículos semi-novos de todas as marcas e modelos, revisados, com garantia e procedência. Caldarelli Veículos atua no mercado a mais de 10 anos, trazendo qualidade e um diferencial em veículos semi-novos. Disponibilizamos as melhores taxas e condições de financiamento nas principais operadoras do mercado. Aceitamos carta de crédito, seu veículo como forma de pagamento. Contamos com uma excelente equipe para melhor atende-lo, venha nos fazer uma visita, ou entre em contato pelos telefones: (43) 3324 6001 (43) 3329 9001. Embora a prática rigorosa na acuidade, precisão, exibição e atualização de dados gerais, informações e conteúdo dispostos no site, nos reservamos o direito a correções de possíveis erros de digitação, omissão de dados ou qualquer informação que venha a ser questionada por ser tratar de veiculo semi novo.",
  shift: "Automático",
  carImages: [
    {
      id: "1",
      imageUrl: "https://s3.carro57.com.br/FC/3215/7282475_0_B_42390ff95a.jpeg",
    },
    {
      id: "2",
      imageUrl: "https://s3.carro57.com.br/FC/3215/7282475_1_B_473e85fcc5.jpeg",
    },
    {
      id: "3",
      imageUrl: "https://s3.carro57.com.br/FC/3215/7282475_2_B_dc2163b7fe.jpeg",
    },
    {
      id: "4",
      imageUrl: "https://s3.carro57.com.br/FC/3215/7282475_3_B_41ad9f0419.jpeg",
    },
    {
      id: "5",
      imageUrl: "https://s3.carro57.com.br/FC/3215/7282475_9_B_abda62fc98.jpeg",
    },
    {
      id: "6",
      imageUrl: "https://s3.carro57.com.br/FC/3215/7282475_5_B_96b8f75475.jpeg",
    },
    {
      id: "7",
      imageUrl: "https://s3.carro57.com.br/FC/3215/7282475_5_B_96b8f75475.jpeg",
    },
    {
      id: "8",
      imageUrl: "https://s3.carro57.com.br/FC/3215/7282475_6_B_5f06d12371.jpeg",
    },
    {
      id: "9",
      imageUrl: "https://s3.carro57.com.br/FC/3215/7282475_7_B_1e1bfed6ee.jpeg",
    },
    {
      id: "10",
      imageUrl: "https://s3.carro57.com.br/FC/3215/7282475_8_B_19815f0388.jpeg",
    },
    {
      id: "11",
      imageUrl: "https://s3.carro57.com.br/FC/3215/7282475_9_B_ab2aadcd99.jpeg",
    },
  ],
  liked: "true",
};
